// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK22cxO8FDkAm6NbyMcBV__hhbDtUn6pY',
    appId: '1:1030920972906:android:9830aa6d177db910b77813',
    messagingSenderId: '1030920972906',
    projectId: 'oz-player',
    storageBucket: 'oz-player.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRFztM8Mkb14nmRdvsrFIPEgMNRSr0kWc',
    appId: '1:1030920972906:ios:daabf72d390e4ebeb77813',
    messagingSenderId: '1030920972906',
    projectId: 'oz-player',
    storageBucket: 'oz-player.firebasestorage.app',
    androidClientId: '1030920972906-s84q0hspn0gl972qa5h8cmgvgel0b0nh.apps.googleusercontent.com',
    iosClientId: '1030920972906-lmrobs01kau10bqi70jpm61lvv060gm8.apps.googleusercontent.com',
    iosBundleId: 'com.oz.ozplayer',
  );

}